baseURL: "https://plasma-lab.netlify.app/"
languageCode: en-us
title: "ĞŸĞ»Ğ°Ğ·Ğ¼Ğ°!!!"
menu:
  main:
    - name: "ğŸ¡ Ğ”Ğ¾Ğ¼Ğ¾Ğ¹ [h]"
      url: /
      weight: 1
    # - name: categories
    #   url: "categories/"
    #   weight: 2
    # - name: tags
    #   url: "tags/"
    #   weight: 3
    # - name: "ğŸ“˜ Bookmarks"
    #   url: /bookmarks
    #   weight: 4
    # - name: "ğŸ“ ĞšĞ¾Ğ½Ñ‚Ğ°ĞºÑ‚"
    #   url: "https://t.me/AprilHamer"
    #   weight: 5

params:
  description: "ĞŸĞ»Ğ°Ğ·Ğ¼ĞµĞ½Ğ½Ñ‹Ğµ Ñ‚ĞµÑ…Ğ½Ğ¾Ğ»Ğ¾Ğ³Ğ¸Ğ¸"

markup:
  highlight:
    codeFences: true
    style: bw
    lineNumbersInTable: false
    noClasses: true
  goldmark:
    renderer:
      unsafe: true

module:
  imports:
    - path: github.com/barklan/hugo-dead-simple
